### ISSUE TITLE
Numary UI

### ISSUE THREAD

**Issue by thephilluk** [numary/ledger#22]
HI there,

I tried opening the Dashboard via the SSH  link i have, but it just came up with the following error: 
`2021/07/22 12:57:08 exec: "xdg-open": executable file not found in $PATH`
I have already changed the HTML bind address to the external IP.
Is there some URL I can visit to open the Dashboard or does it have to be started manually?

thanks,
Philip

**Comment by altitude** [comment]
Hey @thephilluk,

This was an issue with xdg-open sometimes not existing on ubuntu-server, this gets fixed with Alpha 24 - will just cost you another curl :)

Thanks for the heads up!

Cheers,

**Comment by thephilluk** [comment]
Hi,
thats great, but it seems to just bind to localhost, not the address in the config.
```
numary ui
Numary control is live on http://localhost:3078
```

tried connecting with the external ip, but i get an  empty response.
thanks,
Philip

**Comment by altitude** [comment]
Ha that' right, the address in config is actually used for the ledger http api and not the UI. Adding a new parameter to achieve this (see #24) - should be ready in the afternoon.

Cheers!

**Comment by altitude** [comment]
Alright this is now available in Alpha 25 @thephilluk 

**With env**
```
NUMARY_UI_HTTP_BIND_ADDRESS=localhost:3070 \
numary ui
```

**With config file**
```
ui:
  http:
    bind_address: localhost:3070
```

Thanks for bringing that up!

**Comment by daninfpj** [comment]
Thanks for the fix.

I was following the README and ran into this (if the server is running the port is already in use, if it’s not the UI start but has nothing to connect to).

Maybe it would be helpful to have a different default port in the UI? Or document it in the README? IMO It would make for a better first-time experience if you could follow the Getting Started guide and have both things running immediately with no friction.
