### ISSUE TITLE
Numary UI not displaying any Data

### ISSUE THREAD

**Issue by thephilluk** [numary/ledger#27]
Hi there,

i tried displaying the UI right now and it comes up with this: 
![image](https://user-images.githubusercontent.com/35992773/126704280-f873fee1-8234-47f9-aaea-7ee9cdcf147d.png)

there is data in the quickstart ledger: 
`{"cursor":{"page_size":15,"has_more":false,"total":3,"remaning_results":0,"data":[{"address":"world","contract":"default"},{"address":"users:001","contract":"default"},{"address":"central_bank","contract":"default"}]},"ok":true}`

**Comment by altitude** [comment]
Hey @thephilluk,

Interesting one! Could you share more details on your setup? i.e. are you running the server & ui locally or on remote machine?

**Comment by thephilluk** [comment]
Hey @altitude,

i am running the server on my windows machine through wsl (technically a separate machine).
So i open two terminals, in one i run `numary server start`, in the other i run `numary ui` and open my webbrowser on my windows machine and visit the url set in the config.

**Comment by altitude** [comment]
Hey @thephilluk,

I believe this may be an issue with Control going straight to `localhost:3068`- just to be sure, when you spin your browser, what endpoint can you hit to get a response from the numary server?

**Comment by thephilluk** [comment]
Hi @altitude,

I have to request from 192.168.178.210 as it is technically a separate machine.

**Comment by thephilluk** [comment]
Hi @altitude, wanted to check on an update for this?

**Comment by altitude** [comment]
Hi @thephilluk! Apologies for the late rep, we got the issue reproduced and are working on a fix to make Control able to communicate with any address. Will merge & notify you back by later this week!

**Comment by altitude** [comment]
Hi @thephilluk, circling back on this :) We're working on a big update for Control but in the meantime, just added a way to connect to any ledger from the console:

```JS
localStorage['ledger_uri'] = 'http://localhost:3055'; // defaults to "http://localhost:3068"
localStorage['ledger_name'] = 'foobar'; // defaults to "quickstart"
```
