### ISSUE TITLE
Feature Request: GET /{ledger}/transactions filtered by account or transaction ID?

### ISSUE THREAD

**Issue by karmanyaahm** [numary/ledger#30]
This would be useful - for example - to show a user their transaction history, or to see a specific transaction.

**Comment by altitude** [comment]
Hey @karmanyaahm,

Great feedback - so there's an (undocumented yet) account query param for the GET /{ledger}/transactions, e.g. `/quickstart/transactions?account=users:001`.

The transaction id makes sense, we'll add it shortly.

**Comment by djimnz** [comment]
New GetTransaction API Endpoint to retrieve a ledger transaction by transaction ID (txid).

#81
