### ISSUE TITLE
Adding a description/custom id to transactions?

### ISSUE THREAD

**Issue by karmanyaahm** [numary/ledger#31]
I think numary is the right fit for a project I'm planning on, and I'm wondering if adding descriptions (and perhaps filtering by them in GET /{ledger}/transactions see #30 ) would be a planned feature? In my case, it would be useful to correlate the initial set of transactions from a public blockchain to the internal numary ledger.

For both this and #30, I could try a PR when I get to coding the accounting part of my project. (that is, if you consider these features would be useful as part of numary)

**Comment by altitude** [comment]
Hey @karmanyaahm,

These features most definitely make sense for Numary - we're currently working on adding arbitrary key/value transactions metadata, which should cover your needs for reconciling.

Thanks for the heads up! And happy to make sure that the implementation works for you - we'll link the RFC shortly.

**Comment by gfyrag** [comment]
@karmanyaahm The current version of the ledger add metadata. Can we close this issue?

**Comment by karmanyaahm** [comment]
I hadn't looked at recently releases. That's amazing, thanks!
