### ISSUE TITLE
SaveMeta should include an ID and timestamp

### ISSUE THREAD

**Issue by henry-jackson** [numary/ledger#63]
**Is your feature request related to a problem? Please describe.**
Currently metadata records are not assigned an ID or timestamp when saved to the ledger's DB.

**Solution proposal**
Similar to other methods on the ledger, add logic to calculate the next metadata ID. Add this to the ID field of the record. Get the current system time and add the timestamp to the record as well. 

To do this we would either need to update the [storage.Store interface's SaveMeta method](https://github.com/numary/ledger/blob/main/storage/storage.go#L20) to accept an ID and timestamp, or change the [core.Metadata](https://github.com/numary/ledger/blob/main/core/metadata.go#L5) type to be a struct which has an ID and timestamp as fields in addition the the map[string]json.RawMessage.

**Comment by altitude** [comment]
Merged with #64!
