### ISSUE TITLE
Query parameter Account is ignored

### ISSUE THREAD

**Issue by S0c5** [numary/ledger#70]
**Describe the bug**
When I query `get /transactions?account=some-account-here` it ignore the account query parameter

**To Reproduce**
curl --request GET \ 
     --url 'http://localhost:3068/quickstart/transactions?account=211212' \
     --header 'Accept: application/json' | jq

**Expected behavior**
return the transactions that match with the desired account

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: BigSur
 - Numary Version
 ```
 Version: 1.0.0-beta.11 
Date: 2021-11-23T11:54:22Z 
Commit: 48ca56b 
```

**Comment by altitude** [comment]
Fixed by #71 - thanks @S0c5!
